services:
  debian:
    build:
      context: .
      dockerfile: Dockerfile.ci
    command: tail -f /dev/null
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - shared_network
    environment:
      ENV_ID: ${CI_PIPELINE_ID:-xx}

networks:
  shared_network:
    name: shared_network-${ENV_ID:-xx}
