---
targets:
  main:
    resources:
    - NetworkService:
        # The actual address will be filled in by the strategy
        address: ''
        port: 22
        username: root

    drivers:
    - QEMUDriver:
        qemu_bin: qemu-amd64
        machine: pc
        cpu: core2duo
        memory: 2G
        extra_args: "-accel kvm"
        nic: user,model=virtio-net-pci
        disk: disk-image
    - ShellDriver:
        login_prompt: 'Please press Enter to activate this console.'
        username: 'root'
        prompt: 'root@OpenWrt:[^ ]+# '
        login_timeout: 200
    - SSHDriver: {}
    - QEMUNetworkStrategy: {}

tools:
  qemu-amd64: /usr/bin/qemu-system-amd64

images:
  disk-image: ../openwrt.img

urls:
  disk-image: >
    https://downloads.openwrt.org/releases/23.05.4/targets/x86/64/openwrt-23.05.4-x86-64-generic-ext4-combined.img.gz

imports:
- ../util/strategy/qemunetworkstrategy.py
