targets:
  main:
    resources:
    - NetworkService:
        # The actual address will be filled in by the strategy
        address: ''
        port: 22
        username: root
    - QEMUParams:
        overwrite: true

    drivers:
    - CustomQEMUDriver:
        qemu_bin: qemu-amd64
        machine: pc
        cpu: core2duo
        memory: 2G
        extra_args: >-
          -device virtio-net-pci,netdev=net0 -netdev user,id=net0,net=10.0.2.0/24,dhcpstart=10.0.2.100
        disk: disk-image
    - ShellDriver:
        login_prompt: 'Please press Enter to activate this console.'
        username: 'root'
        prompt: 'root@OpenWrt:[^ ]+# '
        login_timeout: 200
    - SSHDriver:
        explicit_scp_mode: true
    - QEMUNetworkStrategy: {}

tools:
  qemu-amd64: /usr/bin/qemu-system-x86_64

images:
  disk-image: ../openwrt.img

urls:
  # disk image is assumed to be in .gz format
  disk-image: http://artifacts:8000/openwrt-23.05.4-x86-64-generic-ext4-combined.img.gz

imports:
- driver
- strategy
