FROM python:3.13-bookworm

LABEL org.opencontainers.image.authors="Rainer Poisel <rainer@honeytreelabs.com>"

RUN <<EOT
apt-get update -qy
apt-get install -qyy \
    -o APT::Install-Recommends=false \
    -o APT::Install-Suggests=false \
        curl
EOT

COPY requirements.txt /requirements.txt

RUN pip install -r /requirements.txt

COPY ./artifacts.yaml /artifacts.yaml
COPY ./artifacts /artifacts_srv

CMD ["python", "/artifacts_srv"]
